using System;

namespace DBConverter
{
    partial class Program
    {
        enum MODULE_ATTRIBUTES
        {
            MODULE_ATTRIBUTE_POLARIZED,

            MODULE_ATTRIBUTE_SHIELD_EM_RESIST,
            MODULE_ATTRIBUTE_SHIELD_THERMAL_RESIST,
            MODULE_ATTRIBUTE_SHIELD_KINETIC_RESIST,
            MODULE_ATTRIBUTE_SHIELD_EXPLOSIVE_RESIST,

            MODULE_ATTRIBUTE_ARMOR_EM_RESIST,
            MODULE_ATTRIBUTE_ARMOR_THERMAL_RESIST,
            MODULE_ATTRIBUTE_ARMOR_KINETIC_RESIST,
            MODULE_ATTRIBUTE_ARMOR_EXPLOSIVE_RESIST,

            MODULE_ATTRIBUTE_HULL_EM_RESIST,
            MODULE_ATTRIBUTE_HULL_THERMAL_RESIST,
            MODULE_ATTRIBUTE_HULL_KINETIC_RESIST,
            MODULE_ATTRIBUTE_HULL_EXPLOSIVE_RESIST,

            MODULE_ATTRIBUTE_SHIELD_BONUS_ADD,
            MODULE_ATTRIBUTE_ARMOR_BONUS_ADD,
            MODULE_ATTRIBUTE_HULL_BONUS_ADD,

            MODULE_ATTRIBUTE_SHIELD_BONUS_MULTIPLY,
            MODULE_ATTRIBUTE_ARMOR_BONUS_MULTIPLY,
            MODULE_ATTRIBUTE_HULL_BONUS_MULTIPLY,

            MODULE_ATTRIBUTE_SHIP_TYPE,
            MODULE_ATTRIBUTE_HIGH_SLOTS,
            MODULE_ATTRIBUTE_MEDIUM_SLOTS,
            MODULE_ATTRIBUTE_LOW_SLOTS,

            MODULE_ATTRIBUTE_SHIELD_HARDENERS_OVERLOAD_BONUS,
            MODULE_ATTRIBUTE_ARMOR_HARDENERS_OVERLOAD_BONUS,
        };
    }
}