<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>EveFitScanUI</RootNamespace>
    <AssemblyName>EveFitScanUI</AssemblyName>
    <ApplicationIcon>ship_scan.ico</ApplicationIcon>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Deterministic>true</Deterministic>
    <SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
    <NoWarn>$(NoWarn);CA1416</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="HtmlAgilityPack" Version="1.11.61" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="8.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\EveFitScan.Core\EveFitScan.Core.csproj" />
    <ProjectReference Include="..\SdeConverter\SdeConverter.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="ship_scan.ico" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator></Generator>
    </None>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>true</DesignTimeSharedInput>
      <AutoGen>false</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>
